### ISSUE TITLE
Fails to run on macOS

### ISSUE THREAD

**Issue by bestlem** [emacs-twist/nix3.el#1]
I could not load this at all.

The error is due to not being able to set nix3-registry-user-file.

I note that `nix registry list` does work on macOS but there does not seem to be a user local file - the global one exists but is empty.

Do we need to have registery functions for other part of nix3 to work?

**Comment by akirak** [comment]
> The error is due to not being able to set nix3-registry-user-file.

Yes, I have not provided the default value for Mac yet, so it would fail to load.

Could you please send me a PR to provide the value of `nix3-registry-user-file` (and possibly `nix3-registry-system-file`) for Mac? I don't have any machine that runs Mac, so I can't test it. Sorry for the trouble.

You only have to add a new pattern for `darwin` in the following expression:

```emacs-lisp
(defcustom nix3-registry-user-file
  (cl-case system-type
    (gnu/linux
     (progn
       (require 'xdg)
       (expand-file-name "nix/registry.json" (xdg-config-home))))
    (otherwise
     (error "Not defined for %s" system-type)))
  ""
  :type 'file)
```

Thanks,

**Comment by bestlem** [comment]
I have a flakes setup - I don't think I have a nix registry file. The system is as nixOS but has no values
nix registry list does work though.

I am a beginner at nix so don't understand it all.

Looking at https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-registry.html I would suggest setting it to the same as Linux. At least let nix3.el load even if not used.

**Comment by akirak** [comment]
Do you have `xdg` library in Emacs on Mac?

**Comment by akirak** [comment]
I have pushed a new commit that is supposed to fix the issue. If it has fixed, please close this issue.

**Comment by akirak** [comment]
Also note, if you don't understand Nix at all, then this package is probably not for you. The package is still experimental, and its features are subject to change. I would recommend you to use command line on terminal. Sorry.

**Comment by bestlem** [comment]
That change did allow the emacs part to run.

My problem is now that I have not got nix on the exec-path so I can't test more. This is the usual issue of PATH differing between terminal and apps launched from Finder - I have changed my zsh setup away from usual enough to confuse nix so I need to fix that first. So I'll stick to command line

**Comment by akirak** [comment]
Thanks for reporting.
