### ISSUE TITLE
Package-Requires need to be one line only

### ISSUE THREAD

**Issue by bestlem** [emacs-twist/nix3.el#2]
In nix3.l your Package-Requires spread over two lines.

Unfortunately the Emacs manual https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html
says "Its format is a list of lists on a single line. "

When I install nix3.el it did not load promise from an elpa repo until I made it all one line.

**Comment by akirak** [comment]
What package manager are you using?

Actually, some packages ([epkg](https://github.com/emacscollective/epkg/blob/main/lisp/epkg.el) for example) have a `Package-Requires` header that spans on multiple lines, and it is valid in `package.el`. `package.el` uses `lm-header-multiline` function to parse the header, and it reads strings from multiple continuous lines.

I am not sure if the specification should be strictly applied. If it is mandatory, I will have to follow the spec, but it will involve updates in many projects. Multi-line package-requires headers are valid in `package.el` and my package manager, twist.nix.

**Comment by bestlem** [comment]
I was using straight.el but the Emacs manual page would be package.el 

All the packages I use are one liners - in the case of treemacs a long one-liner. except parts of magit but I think they get regenerated by a Makefile

**Comment by akirak** [comment]
I find it strange but fixed it. Thanks again.

**Comment by bestlem** [comment]
OK I found the fix in package.el that made it multiline in 2019 - However documentation seems not to have been updated and obviously other package managers have not read it (or they predate that change)

And the newest package manager elpaca seems to be single line only (but the code is more complex that package.el) If I try that again I'll report the bug if it does exist.

**Comment by akirak** [comment]
> OK I found the fix in package.el that made it multiline in 2019 - However documentation seems not to have been updated and obviously other package managers have not read it (or they predate that change)

So I didn't have to make the change, but it doesn't break anything either. Thanks.
